### ISSUE TITLE
Port SOR from b-sdk

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#384]

**Comment by franzns** [comment]
https://github.com/beethovenxfi/beethovenx-backend/pull/333

**Comment by gmbronco** [comment]
v2 needs:

- [ ] Base config
- [x] See why Avalanche FX pool data is missing in subgraph (FX pool token does not have latestFXPrice) - b-sdk expects a property `token { latestFXPrice }` on a poolToken item. - #565 
- [x] Optimism stable pool adapter is throwing, [asana issue](https://app.asana.com/0/1201380039585484/1205971750518367)
- [x] Handle failing paths with 'Swap amount exceeds the pool limit' - https://github.com/balancer/b-sdk/pull/158

V1:
- [ ] fantom has some issues with bignumber, need to investigate

couldn't test on zkevm, because tenderly doesn't fork it, will try with a local fork
