### ISSUE TITLE
remove chain from veBAL models

### ISSUE THREAD

**Issue by mendesfabio** [beethovenxfi/beethovenx-backend#498]
Another thing I found confusing is the `chain` field from `PrismaVeBalUserBalance` and `PrismaVeBalTotalSupply` models. I don't think it causes any issues right now since veBAL page is only accessible on Mainnet, but it makes possible for users to have different veBAL rank on different blockchains. For instance, Humpy is 2nd on Ethereum, but if I query the rank on Polygon:

<img width="1009" alt="image" src="https://github.com/beethovenxfi/beethovenx-backend/assets/43360747/46ec993f-6aec-4c88-90c4-cd81f3fdd54a">

TBH I'm not saying we _have_ to remove it, but wanted to open this issue to understand the reasoning behind this field, maybe I'm missing something important.

**Comment by franzns** [comment]
The reason this is added is because different chains have different veBAL total supply and different userBalances because of the syncing process. When all chains are in sync then yes, the users have the same rank on all networks. 

Maybe a lock expired but the balances have not been synced by anybody yet. 

Is my understanding correct here?
