### ISSUE TITLE
TVL of V1 does not match V2

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beethovenx-backend#60]
There is some discrepancy between the TVL on current (V1) backend vs our V2 implementation

**Comment by franzns** [comment]
seems pretty random. some pools have more tvl on v2 other pools have less tvl on v2. all pool types seem to be affected. 

Investigating Fidelio Duetto. 

TVL:
v1: "totalLiquidity": "8809979.119572287"
v2: "totalLiquidity": "8849997.407530082"

BeetsPrice:
v1: 0.086975
v2: 0.087165

wftm price:
v1: 0.374353
v2: 0.374452

Token prices on v2 are higher, which leads to higher TVL of this pool. I assume due to caching, seems ok.


Investigating Linear Pools:
Linear pools are counted towards the TVL and therefore TVL is inflated in v2. Fix for this is pushed

**Comment by franzns** [comment]
I wrote a debug script that loops through all pools (excluding linear pools) queried from the backend and sums up the TVL. There is still quite some discrepancy in v2, both between summed and metric TVL as well as between v1 and v2 TVL. Some of it can be related to price fluctuations, since v1 and v2 use different price fetching and caching intervals. But the diff is too high to only be that:

```
v1 TVL from metrics: 67371903.30826175
v1 TVL from pool sum: 67372216.18523617
v2 TVL from metrics: 73319423.69128639
v2 TVL from pool sum: 69792198.61742367
```


Further investigation showed a few pools that have more than 100k discrepancy between v1 and v2:

Pool name: Pirate in C
Pool address: 0xeadcfa1f34308b144e96fcd7a07145e027a8467d
Pool type: PHANTOM_STABLE
v1 TVL: 572136.623728712
v2 TVL: 285522.9118637205
TVL diff (v1 - v2): 286613.71186499146
---------------------
Pool name: Mint Dapcash
Pool address: 0x07fc9e1a6236a400a28956d4d924f68dadc329d8
Pool type: WEIGHTED
v1 TVL: 0
v2 TVL: 998214.137824443
TVL diff (v1 - v2): -998214.137824443
---------------------
Pool name: 80SOLACE-20WETH
Pool address: 0x8d827c4f1c88141bc8f75ac1ffe1c201e09b07bb
Pool type: WEIGHTED
v1 TVL: 53621.344081477575
v2 TVL: 274685.7079217095
TVL diff (v1 - v2): -221064.36384023193
---------------------
Pool name: Poltergeist Liquidity
Pool address: 0x8de0c333f99459fc206398d84625ac05c61c190e
Pool type: WEIGHTED
v1 TVL: 0
v2 TVL: 1227565.418034857
TVL diff (v1 - v2): -1227565.418034857


More investigation will follow.

**Comment by franzns** [comment]
https://v2.beets.fi/pool/0x07fc9e1a6236a400a28956d4d924f68dadc329d8000200000000000000000109
https://v2.beets.fi/pool/0x8de0c333f99459fc206398d84625ac05c61c190e0002000000000000000004d4

They have 0 everything in v1 and some stats at least in v2. 
in v2, tokens don't show a balance, but the pool does.

these two pools account for 2M tvl discrepancy

**Comment by franzns** [comment]
Same with this pool: https://v2.beets.fi/pool/0x8d827c4f1c88141bc8f75ac1ffe1c201e09b07bb0002000000000000000004cc solace token doesn't have a balance, but TVL is there

**Comment by franzns** [comment]
I think I found it, seems to be related to white_listed tokens. If a token is not white listed, it won't get a balance in the UI but it will still be counted towards the TVL of that pool.

**Comment by franzns** [comment]
Other TVL discrepancy comes from pricing interest bearing assets, such as liHND. We didn't have prices for them in v1 but have them in v2, therefore TVL is higher.

**Comment by 0xSkly** [comment]
full investigation mode 👍  not sure what we should do with the whitelisted tokens in regard to tvl, also maybe something to talk with souvlaki about

**Comment by franzns** [comment]
seems like these tokens (SOLACE, DAPCASH etc.) are in the PrismaTokenCurrentPrice table which is used to calculate pool TVL but they are missing from the PrismaTokenDynamicData table, which, I assume, is used to render the pool page.

**Comment by franzns** [comment]
Ok, all seems good. We decided that we leave these three pools in there for now.

Also, there are more pools on v2 because there is no filtering (like no minimum tvl) which was the case in v1.

A few things remain: 
- cLQDR pricing
- Why summed up pool tvl is less that metrics tvl

**Comment by franzns** [comment]
cLQDR pricing is synced from onchain in v2, yielding better results and more accurate TVL.

TVL from summed up pools ~3.5M lower than TVL in metrics. Did not find out why, code is essentially the same. Maybe @danielmkm has an idea why?

**Comment by franzns** [comment]
opened #72 to keep track of the remaining issue, closing this.
